export const LOGIN_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const LOGIN_REQUEST = "ALL_PRODUCT_REQUEST"
export const LOGIN_FAIL = "ALL_PRODUCT_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST "
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS "
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL "

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST "
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS "
export const LOAD_USER_FAIL = "LOAD_USER_FAIL "

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS "
export const LOGOUT_FAIL = "LOGOUT_FAIL "

export const UPDATE_PROFILE_REQUEST = "REGISTER_USER_REQUEST "
export const UPDATE_PROFILE_SUCCESS = "REGISTER_USER_SUCCESS "
export const UPDATE_PROFILE_FAIL = "REGISTER_USER_FAIL "
export const UPDATE_PROFILE_RESET = "REGISTER_USER_RESET"

export const UPDATE_PASSWORD_REQUEST = "USER_PASSWORD_REQUEST "
export const UPDATE_PASSWORD_SUCCESS = "USER_PASSWORD_SUCCESS "
export const UPDATE_PASSWORD_FAIL = "USER_PASSWORD_FAIL "
export const UPDATE_PASSWORD_RESET = "USER_PASSWORD_RESET"

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS"
export const ALL_USERS_FAIL = "ALL_USERS_FAIL"

export const  USER_DETAILS_FAIL = " USER_DETAILS_FAIL"
export const  USER_DETAILS_SUCCESS  = "USER_DETAILS_SUCCESS"
export const  USER_DETAILS_REQUEST = " USER_DETAILS_REQUEST"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"
export const DELETE_USER_RESET = "DELETE_USER_RESET"
